export function textSizeProps(size: any) {
    return size === "289"
        ? "text-289"
        : size === "156"
        ? "text-156"
        : size === "150"
        ? "text-150"
        : size === "100"
        ? "text-100"
        : size === "89"
        ? "text-89"
        : size === "60"
        ? "text-60"
        : size === "52"
        ? "text-52"
        : size === "49"
        ? "text-49"
        : size === "40"
        ? "text-40"
        : size === "40"
        ? "text-40"
        : size === "32"
        ? "text-32"
        : size === "28"
        ? "text-28"
        : size === "25"
        ? "text-25"
        : size === "24"
        ? "text-24"
        : size === "22"
        ? "text-22"
        : size === "21"
        ? "text-21"
        : size === "20"
        ? "text-20"
        : size === "18"
        ? "text-18"
        : "text-16";
}

export function textVariantProps(variant: any) {
    return variant === "light"
        ? "text-light"
        : variant === "white"
        ? "text-white"
        : "text-dark";
}
